apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    curso: edc
    app: meunginx # label para vincular o service
spec:
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: webports # Podemos definir o servico pelo nome
        containerPort: 80
        protocol: TCP
