apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: LoadBalancer
  selector:
    app: meunginx
  ports:
  - port: 8002 # Exposto nessa porta
    targetPort: webports  # Porta do container/pod (80) ou o nome da porta do container
    protocol: TCP
