apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticia-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistema-noticias
  template:
    metadata:
      name: pod-sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
      - name: containe-sistema-noticias
        image: aluracursos/sistema-noticias:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: configmap-sistema
