apiVersion: v1
kind: Pod
metadata:
  name: pod-portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: containers-portal-noticias
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: configmap-portal
