apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec: #Spec deployment
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template: #Aqui inicia o(s) pod(s) que será(ão) deployados 
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
