apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: container-webapp
        image: nanajanashia/k8s-demo-app:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret   # Nome do secret de referencia
                key: mongo-user  # match do valor definido do secret
          - name: USER_PWD
            valueFrom:
              secretKeyRef:
                name: mongo-secret   # Nome do secret de referencia
                key: mongo-password  # match do valor definido do secret
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
        

--- 
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp # para dar match com a label do deployment que estamos dando acesso.
  ports:
    - protocol: TCP
      port: 3000       # Onde eu recebo a requisiçao
      targetPort: 3000 # Para onde eu encaminho a requisição. Match com a port do container
      nodePort: 30100  # Porta para acesso Externo no cluster
