apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
# Especificação do Deployment
spec:
  replicas: 3
  # Seleção dos Pods que serão tutelados pelo deployment
  selector:
    matchLabels:
      app: portal-noticias
  # Espeficicação do Pod tutelado pelo deployment
  template:
    metadata:
      name: pod-portal-noticias
      labels:
        app: portal-noticias
    spec:                 # Especifica o conteúdo do pod
      containers:
      - name: containers-portal-noticias
        image: aluracursos/portal-noticias:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:            # Porta de Acesso ao Container
          - containerPort: 80
        envFrom:          # Busca Variaveis de ambiente
          - configMapRef: # busca de dentro do arquivo com name: configmap-portal
              name: configmap-portal
